
INSERT INTO unit (ID_UNIT, UNIT) VALUES (1, 'Bed Cover');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (2, 'CPR');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (3, 'Da');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (4, 'Gorden');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (5, 'HD');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (6, 'Jaket');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (7, 'Jas');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (8, 'Kambal');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (9, 'Karpet');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (10, 'Kg');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (11, 'Melar');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (12, 'RSE');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (13, 'Selimut');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (14, 'Sepatu');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (15, 'Seprai');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (16, 'Tas');
INSERT INTO unit (ID_UNIT, UNIT) VALUES (17, 'Tikar');
