
INSERT INTO paket (ID_PAKET, PAKET) VALUES (1, '?');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (2, '3X/EX');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (3, '9S');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (4, 'Cuci Basah');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (5, 'Cuci Kering');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (6, 'Cuci Setrika');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (7, 'Dry Clean');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (8, 'LTA');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (9, 'Setrika');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (10, 'SL');
INSERT INTO paket (ID_PAKET, PAKET) VALUES (11, 'Toe n Tas');
